name: Michael Whalen
favicon: null
layout_spectrum: 0.43402
typography_spectrum: 0.03083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ee6c4d'
    - '#293241'
    - '#3d5a80'
    - '#98c1d9'
    - '#e0fbfc'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
