name: Michael Whalen
favicon: null
layout_spectrum: 0
typography_spectrum: 0.03083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4e6582'
    - '#b2b6ab'
    - '#c99342'
    - '#9a612a'
  brandStrength: 0.12136487639509141
  lightness: 0.030938887735828757
  saturation: 0.6934588688891381
  rhythmicContrast: 0.9287289038766176
purpose: []
