name: Michael Whalen
favicon: null
layout_spectrum: 0.23851
typography_spectrum: 0.03083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030305'
    - '#6b7994'
    - '#3c4969'
    - '#fefefe'
    - '#c0c0be'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
