name: Michael Whalen
favicon: null
layout_spectrum: 0.23851
typography_spectrum: 0.03083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ee6c4d'
    - '#293241'
    - '#3d5a80'
    - '#98c1d9'
    - '#e0fbfc'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
