name: Michael Whalen
favicon: null
layout_spectrum: 0.35973
typography_spectrum: 0.12076
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ee6c4d'
    - '#293241'
    - '#3d5a80'
    - '#98c1d9'
    - '#e0fbfc'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
